# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forumgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('forum_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forums.ForumGroup')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='forums.Site')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forum',
            unique_together=set([('site', 'source_reference')]),
        ),
    ]
