# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_reference', models.CharField(db_index=True, max_length=255)),
                ('title', models.TextField(blank=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forums.Forum')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('forum', 'source_reference')]),
        ),
    ]
